/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AsistenciaRouteImport } from './routes/asistencia'
import { Route as CongregadosRouteImport } from './routes/congregados'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EscanearRouteImport } from './routes/escanear'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaterialesRouteImport } from './routes/materiales'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ConfiguracionSuscripcionRouteImport } from './routes/configuracion/suscripcion'
import { Route as EventosEventIdAsistenciaRouteImport } from './routes/eventos.$eventId.asistencia'
import { Route as EventosEventIdQrRouteImport } from './routes/eventos.$eventId.qr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenciaRoute = AsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => rootRouteImport,
} as any)
const CongregadosRoute = CongregadosRouteImport.update({
  id: '/congregados',
  path: '/congregados',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EscanearRoute = EscanearRouteImport.update({
  id: '/escanear',
  path: '/escanear',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialesRoute = MaterialesRouteImport.update({
  id: '/materiales',
  path: '/materiales',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionSuscripcionRoute =
  ConfiguracionSuscripcionRouteImport.update({
    id: '/configuracion/suscripcion',
    path: '/configuracion/suscripcion',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventosEventIdAsistenciaRoute =
  EventosEventIdAsistenciaRouteImport.update({
    id: '/$eventId/asistencia',
    path: '/$eventId/asistencia',
    getParentRoute: () => EventosRoute,
  } as any)
const EventosEventIdQrRoute = EventosEventIdQrRouteImport.update({
  id: '/$eventId/qr',
  path: '/$eventId/qr',
  getParentRoute: () => EventosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/asistencia': typeof AsistenciaRoute
  '/congregados': typeof CongregadosRoute
  '/dashboard': typeof DashboardRoute
  '/escanear': typeof EscanearRoute
  '/eventos': typeof EventosRouteWithChildren
  '/login': typeof LoginRoute
  '/materiales': typeof MaterialesRoute
  '/portal': typeof PortalRoute
  '/privacidad': typeof PrivacidadRoute
  '/registro': typeof RegistroRoute
  '/configuracion/suscripcion': typeof ConfiguracionSuscripcionRoute
  '/eventos/$eventId/asistencia': typeof EventosEventIdAsistenciaRoute
  '/eventos/$eventId/qr': typeof EventosEventIdQrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/asistencia': typeof AsistenciaRoute
  '/congregados': typeof CongregadosRoute
  '/dashboard': typeof DashboardRoute
  '/escanear': typeof EscanearRoute
  '/eventos': typeof EventosRouteWithChildren
  '/login': typeof LoginRoute
  '/materiales': typeof MaterialesRoute
  '/portal': typeof PortalRoute
  '/privacidad': typeof PrivacidadRoute
  '/registro': typeof RegistroRoute
  '/configuracion/suscripcion': typeof ConfiguracionSuscripcionRoute
  '/eventos/$eventId/asistencia': typeof EventosEventIdAsistenciaRoute
  '/eventos/$eventId/qr': typeof EventosEventIdQrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/asistencia': typeof AsistenciaRoute
  '/congregados': typeof CongregadosRoute
  '/dashboard': typeof DashboardRoute
  '/escanear': typeof EscanearRoute
  '/eventos': typeof EventosRouteWithChildren
  '/login': typeof LoginRoute
  '/materiales': typeof MaterialesRoute
  '/portal': typeof PortalRoute
  '/privacidad': typeof PrivacidadRoute
  '/registro': typeof RegistroRoute
  '/configuracion/suscripcion': typeof ConfiguracionSuscripcionRoute
  '/eventos/$eventId/asistencia': typeof EventosEventIdAsistenciaRoute
  '/eventos/$eventId/qr': typeof EventosEventIdQrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/asistencia'
    | '/congregados'
    | '/dashboard'
    | '/escanear'
    | '/eventos'
    | '/login'
    | '/materiales'
    | '/portal'
    | '/privacidad'
    | '/registro'
    | '/configuracion/suscripcion'
    | '/eventos/$eventId/asistencia'
    | '/eventos/$eventId/qr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/asistencia'
    | '/congregados'
    | '/dashboard'
    | '/escanear'
    | '/eventos'
    | '/login'
    | '/materiales'
    | '/portal'
    | '/privacidad'
    | '/registro'
    | '/configuracion/suscripcion'
    | '/eventos/$eventId/asistencia'
    | '/eventos/$eventId/qr'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/asistencia'
    | '/congregados'
    | '/dashboard'
    | '/escanear'
    | '/eventos'
    | '/login'
    | '/materiales'
    | '/portal'
    | '/privacidad'
    | '/registro'
    | '/configuracion/suscripcion'
    | '/eventos/$eventId/asistencia'
    | '/eventos/$eventId/qr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AsistenciaRoute: typeof AsistenciaRoute
  CongregadosRoute: typeof CongregadosRoute
  DashboardRoute: typeof DashboardRoute
  EscanearRoute: typeof EscanearRoute
  EventosRoute: typeof EventosRouteWithChildren
  LoginRoute: typeof LoginRoute
  MaterialesRoute: typeof MaterialesRoute
  PortalRoute: typeof PortalRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RegistroRoute: typeof RegistroRoute
  ConfiguracionSuscripcionRoute: typeof ConfiguracionSuscripcionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistencia': {
      id: '/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AsistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congregados': {
      id: '/congregados'
      path: '/congregados'
      fullPath: '/congregados'
      preLoaderRoute: typeof CongregadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escanear': {
      id: '/escanear'
      path: '/escanear'
      fullPath: '/escanear'
      preLoaderRoute: typeof EscanearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiales': {
      id: '/materiales'
      path: '/materiales'
      fullPath: '/materiales'
      preLoaderRoute: typeof MaterialesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion/suscripcion': {
      id: '/configuracion/suscripcion'
      path: '/configuracion/suscripcion'
      fullPath: '/configuracion/suscripcion'
      preLoaderRoute: typeof ConfiguracionSuscripcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$eventId/asistencia': {
      id: '/eventos/$eventId/asistencia'
      path: '/$eventId/asistencia'
      fullPath: '/eventos/$eventId/asistencia'
      preLoaderRoute: typeof EventosEventIdAsistenciaRouteImport
      parentRoute: typeof EventosRoute
    }
    '/eventos/$eventId/qr': {
      id: '/eventos/$eventId/qr'
      path: '/$eventId/qr'
      fullPath: '/eventos/$eventId/qr'
      preLoaderRoute: typeof EventosEventIdQrRouteImport
      parentRoute: typeof EventosRoute
    }
  }
}

interface EventosRouteChildren {
  EventosEventIdAsistenciaRoute: typeof EventosEventIdAsistenciaRoute
  EventosEventIdQrRoute: typeof EventosEventIdQrRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosEventIdAsistenciaRoute: EventosEventIdAsistenciaRoute,
  EventosEventIdQrRoute: EventosEventIdQrRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AsistenciaRoute: AsistenciaRoute,
  CongregadosRoute: CongregadosRoute,
  DashboardRoute: DashboardRoute,
  EscanearRoute: EscanearRoute,
  EventosRoute: EventosRouteWithChildren,
  LoginRoute: LoginRoute,
  MaterialesRoute: MaterialesRoute,
  PortalRoute: PortalRoute,
  PrivacidadRoute: PrivacidadRoute,
  RegistroRoute: RegistroRoute,
  ConfiguracionSuscripcionRoute: ConfiguracionSuscripcionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
