/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CeoRouteImport } from './routes/ceo'
import { Route as EscanearRouteImport } from './routes/escanear'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as RegisterCongregacionRouteImport } from './routes/registerCongregacion'
import { Route as RegisterstaffRouteImport } from './routes/registerstaff'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as ProtectedAjustesRouteImport } from './routes/_protected.ajustes'
import { Route as ProtectedAsistenciaRouteImport } from './routes/_protected.asistencia'
import { Route as ProtectedCongregadosRouteImport } from './routes/_protected.congregados'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProtectedEventosRouteImport } from './routes/_protected.eventos'
import { Route as ProtectedMaterialesRouteImport } from './routes/_protected.materiales'
import { Route as ProtectedSuscripcionRouteImport } from './routes/_protected.suscripcion'
import { Route as ProtectedEventosEventIdAsistenciaRouteImport } from './routes/_protected.eventos.$eventId.asistencia'
import { Route as ProtectedEventosEventIdQrRouteImport } from './routes/_protected.eventos.$eventId.qr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoRoute = CeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => rootRouteImport,
} as any)
const EscanearRoute = EscanearRouteImport.update({
  id: '/escanear',
  path: '/escanear',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterCongregacionRoute = RegisterCongregacionRouteImport.update({
  id: '/registerCongregacion',
  path: '/registerCongregacion',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterstaffRoute = RegisterstaffRouteImport.update({
  id: '/registerstaff',
  path: '/registerstaff',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAjustesRoute = ProtectedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAsistenciaRoute = ProtectedAsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCongregadosRoute = ProtectedCongregadosRouteImport.update({
  id: '/congregados',
  path: '/congregados',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEventosRoute = ProtectedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMaterialesRoute = ProtectedMaterialesRouteImport.update({
  id: '/materiales',
  path: '/materiales',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSuscripcionRoute = ProtectedSuscripcionRouteImport.update({
  id: '/suscripcion',
  path: '/suscripcion',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEventosEventIdAsistenciaRoute =
  ProtectedEventosEventIdAsistenciaRouteImport.update({
    id: '/$eventId/asistencia',
    path: '/$eventId/asistencia',
    getParentRoute: () => ProtectedEventosRoute,
  } as any)
const ProtectedEventosEventIdQrRoute =
  ProtectedEventosEventIdQrRouteImport.update({
    id: '/$eventId/qr',
    path: '/$eventId/qr',
    getParentRoute: () => ProtectedEventosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ceo': typeof CeoRoute
  '/escanear': typeof EscanearRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/privacidad': typeof PrivacidadRoute
  '/registerCongregacion': typeof RegisterCongregacionRoute
  '/registerstaff': typeof RegisterstaffRoute
  '/registro': typeof RegistroRoute
  '/terminos': typeof TerminosRoute
  '/ajustes': typeof ProtectedAjustesRoute
  '/asistencia': typeof ProtectedAsistenciaRoute
  '/congregados': typeof ProtectedCongregadosRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/eventos': typeof ProtectedEventosRouteWithChildren
  '/materiales': typeof ProtectedMaterialesRoute
  '/suscripcion': typeof ProtectedSuscripcionRoute
  '/eventos/$eventId/asistencia': typeof ProtectedEventosEventIdAsistenciaRoute
  '/eventos/$eventId/qr': typeof ProtectedEventosEventIdQrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ceo': typeof CeoRoute
  '/escanear': typeof EscanearRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/privacidad': typeof PrivacidadRoute
  '/registerCongregacion': typeof RegisterCongregacionRoute
  '/registerstaff': typeof RegisterstaffRoute
  '/registro': typeof RegistroRoute
  '/terminos': typeof TerminosRoute
  '/ajustes': typeof ProtectedAjustesRoute
  '/asistencia': typeof ProtectedAsistenciaRoute
  '/congregados': typeof ProtectedCongregadosRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/eventos': typeof ProtectedEventosRouteWithChildren
  '/materiales': typeof ProtectedMaterialesRoute
  '/suscripcion': typeof ProtectedSuscripcionRoute
  '/eventos/$eventId/asistencia': typeof ProtectedEventosEventIdAsistenciaRoute
  '/eventos/$eventId/qr': typeof ProtectedEventosEventIdQrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/about': typeof AboutRoute
  '/ceo': typeof CeoRoute
  '/escanear': typeof EscanearRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/privacidad': typeof PrivacidadRoute
  '/registerCongregacion': typeof RegisterCongregacionRoute
  '/registerstaff': typeof RegisterstaffRoute
  '/registro': typeof RegistroRoute
  '/terminos': typeof TerminosRoute
  '/_protected/ajustes': typeof ProtectedAjustesRoute
  '/_protected/asistencia': typeof ProtectedAsistenciaRoute
  '/_protected/congregados': typeof ProtectedCongregadosRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/eventos': typeof ProtectedEventosRouteWithChildren
  '/_protected/materiales': typeof ProtectedMaterialesRoute
  '/_protected/suscripcion': typeof ProtectedSuscripcionRoute
  '/_protected/eventos/$eventId/asistencia': typeof ProtectedEventosEventIdAsistenciaRoute
  '/_protected/eventos/$eventId/qr': typeof ProtectedEventosEventIdQrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ceo'
    | '/escanear'
    | '/login'
    | '/portal'
    | '/privacidad'
    | '/registerCongregacion'
    | '/registerstaff'
    | '/registro'
    | '/terminos'
    | '/ajustes'
    | '/asistencia'
    | '/congregados'
    | '/dashboard'
    | '/eventos'
    | '/materiales'
    | '/suscripcion'
    | '/eventos/$eventId/asistencia'
    | '/eventos/$eventId/qr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ceo'
    | '/escanear'
    | '/login'
    | '/portal'
    | '/privacidad'
    | '/registerCongregacion'
    | '/registerstaff'
    | '/registro'
    | '/terminos'
    | '/ajustes'
    | '/asistencia'
    | '/congregados'
    | '/dashboard'
    | '/eventos'
    | '/materiales'
    | '/suscripcion'
    | '/eventos/$eventId/asistencia'
    | '/eventos/$eventId/qr'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/about'
    | '/ceo'
    | '/escanear'
    | '/login'
    | '/portal'
    | '/privacidad'
    | '/registerCongregacion'
    | '/registerstaff'
    | '/registro'
    | '/terminos'
    | '/_protected/ajustes'
    | '/_protected/asistencia'
    | '/_protected/congregados'
    | '/_protected/dashboard'
    | '/_protected/eventos'
    | '/_protected/materiales'
    | '/_protected/suscripcion'
    | '/_protected/eventos/$eventId/asistencia'
    | '/_protected/eventos/$eventId/qr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AboutRoute: typeof AboutRoute
  CeoRoute: typeof CeoRoute
  EscanearRoute: typeof EscanearRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RegisterCongregacionRoute: typeof RegisterCongregacionRoute
  RegisterstaffRoute: typeof RegisterstaffRoute
  RegistroRoute: typeof RegistroRoute
  TerminosRoute: typeof TerminosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo': {
      id: '/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof CeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escanear': {
      id: '/escanear'
      path: '/escanear'
      fullPath: '/escanear'
      preLoaderRoute: typeof EscanearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registerCongregacion': {
      id: '/registerCongregacion'
      path: '/registerCongregacion'
      fullPath: '/registerCongregacion'
      preLoaderRoute: typeof RegisterCongregacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registerstaff': {
      id: '/registerstaff'
      path: '/registerstaff'
      fullPath: '/registerstaff'
      preLoaderRoute: typeof RegisterstaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/ajustes': {
      id: '/_protected/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof ProtectedAjustesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/asistencia': {
      id: '/_protected/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof ProtectedAsistenciaRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/congregados': {
      id: '/_protected/congregados'
      path: '/congregados'
      fullPath: '/congregados'
      preLoaderRoute: typeof ProtectedCongregadosRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/eventos': {
      id: '/_protected/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof ProtectedEventosRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/materiales': {
      id: '/_protected/materiales'
      path: '/materiales'
      fullPath: '/materiales'
      preLoaderRoute: typeof ProtectedMaterialesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/suscripcion': {
      id: '/_protected/suscripcion'
      path: '/suscripcion'
      fullPath: '/suscripcion'
      preLoaderRoute: typeof ProtectedSuscripcionRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/eventos/$eventId/asistencia': {
      id: '/_protected/eventos/$eventId/asistencia'
      path: '/$eventId/asistencia'
      fullPath: '/eventos/$eventId/asistencia'
      preLoaderRoute: typeof ProtectedEventosEventIdAsistenciaRouteImport
      parentRoute: typeof ProtectedEventosRoute
    }
    '/_protected/eventos/$eventId/qr': {
      id: '/_protected/eventos/$eventId/qr'
      path: '/$eventId/qr'
      fullPath: '/eventos/$eventId/qr'
      preLoaderRoute: typeof ProtectedEventosEventIdQrRouteImport
      parentRoute: typeof ProtectedEventosRoute
    }
  }
}

interface ProtectedEventosRouteChildren {
  ProtectedEventosEventIdAsistenciaRoute: typeof ProtectedEventosEventIdAsistenciaRoute
  ProtectedEventosEventIdQrRoute: typeof ProtectedEventosEventIdQrRoute
}

const ProtectedEventosRouteChildren: ProtectedEventosRouteChildren = {
  ProtectedEventosEventIdAsistenciaRoute:
    ProtectedEventosEventIdAsistenciaRoute,
  ProtectedEventosEventIdQrRoute: ProtectedEventosEventIdQrRoute,
}

const ProtectedEventosRouteWithChildren =
  ProtectedEventosRoute._addFileChildren(ProtectedEventosRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAjustesRoute: typeof ProtectedAjustesRoute
  ProtectedAsistenciaRoute: typeof ProtectedAsistenciaRoute
  ProtectedCongregadosRoute: typeof ProtectedCongregadosRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedEventosRoute: typeof ProtectedEventosRouteWithChildren
  ProtectedMaterialesRoute: typeof ProtectedMaterialesRoute
  ProtectedSuscripcionRoute: typeof ProtectedSuscripcionRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAjustesRoute: ProtectedAjustesRoute,
  ProtectedAsistenciaRoute: ProtectedAsistenciaRoute,
  ProtectedCongregadosRoute: ProtectedCongregadosRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedEventosRoute: ProtectedEventosRouteWithChildren,
  ProtectedMaterialesRoute: ProtectedMaterialesRoute,
  ProtectedSuscripcionRoute: ProtectedSuscripcionRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AboutRoute: AboutRoute,
  CeoRoute: CeoRoute,
  EscanearRoute: EscanearRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  PrivacidadRoute: PrivacidadRoute,
  RegisterCongregacionRoute: RegisterCongregacionRoute,
  RegisterstaffRoute: RegisterstaffRoute,
  RegistroRoute: RegistroRoute,
  TerminosRoute: TerminosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
